
import type { CalendarEvent } from './events';

// Pre-computed Gregorian dates for major Buddhist events.
// This data can be updated or replaced with a dynamic calculation library in the future.
export const buddhistEvents: CalendarEvent[] = [
  // 2024
  {
    id: 'buddhist-vesak-2024',
    date: new Date('2024-05-23'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2024',
    date: new Date('2024-02-24'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2024',
    date: new Date('2024-07-21'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2024',
    date: new Date('2024-07-22'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2024',
    date: new Date('2024-10-19'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2024',
    date: new Date('2024-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2024',
    date: new Date('2024-08-18'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2025
  {
    id: 'buddhist-vesak-2025',
    date: new Date('2025-05-12'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2025',
    date: new Date('2025-02-14'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2025',
    date: new Date('2025-07-10'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2025',
    date: new Date('2025-07-11'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2025',
    date: new Date('2025-10-08'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2025',
    date: new Date('2025-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2025',
    date: new Date('2025-09-06'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },
  
  // 2026
  {
    id: 'buddhist-vesak-2026',
    date: new Date('2026-05-31'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2026',
    date: new Date('2026-03-05'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2026',
    date: new Date('2026-06-30'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2026',
    date: new Date('2026-07-01'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2026',
    date: new Date('2026-10-27'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2026',
    date: new Date('2026-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2026',
    date: new Date('2026-08-26'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },
  
  // 2027
  {
    id: 'buddhist-vesak-2027',
    date: new Date('2027-05-21'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2027',
    date: new Date('2027-02-22'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2027',
    date: new Date('2027-07-20'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2027',
    date: new Date('2027-07-21'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2027',
    date: new Date('2027-10-16'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2027',
    date: new Date('2027-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2027',
    date: new Date('2027-08-15'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2028
  {
    id: 'buddhist-vesak-2028',
    date: new Date('2028-05-09'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2028',
    date: new Date('2028-02-11'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2028',
    date: new Date('2028-07-08'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2028',
    date: new Date('2028-07-09'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2028',
    date: new Date('2028-10-05'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2028',
    date: new Date('2028-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2028',
    date: new Date('2028-09-02'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2029
  {
    id: 'buddhist-vesak-2029',
    date: new Date('2029-05-28'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2029',
    date: new Date('2029-03-01'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2029',
    date: new Date('2029-06-27'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2029',
    date: new Date('2029-06-28'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2029',
    date: new Date('2029-10-24'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2029',
    date: new Date('2029-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2029',
    date: new Date('2029-08-23'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2030
  {
    id: 'buddhist-vesak-2030',
    date: new Date('2030-05-18'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2030',
    date: new Date('2030-02-18'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2030',
    date: new Date('2030-07-16'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2030',
    date: new Date('2030-07-17'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2030',
    date: new Date('2030-10-13'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2030',
    date: new Date('2030-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2030',
    date: new Date('2030-08-12'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2031
  {
    id: 'buddhist-vesak-2031',
    date: new Date('2031-05-07'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2031',
    date: new Date('2031-02-07'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2031',
    date: new Date('2031-07-05'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2031',
    date: new Date('2031-07-06'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2031',
    date: new Date('2031-10-02'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2031',
    date: new Date('2031-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2031',
    date: new Date('2031-08-31'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2032
  {
    id: 'buddhist-vesak-2032',
    date: new Date('2032-05-25'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2032',
    date: new Date('2032-02-26'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2032',
    date: new Date('2032-07-23'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2032',
    date: new Date('2032-07-24'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2032',
    date: new Date('2032-10-20'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2032',
    date: new Date('2032-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2032',
    date: new Date('2032-08-19'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2033
  {
    id: 'buddhist-vesak-2033',
    date: new Date('2033-05-15'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2033',
    date: new Date('2033-02-15'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2033',
    date: new Date('2033-07-12'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2033',
    date: new Date('2033-07-13'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2033',
    date: new Date('2033-10-09'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2033',
    date: new Date('2033-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2033',
    date: new Date('2033-09-08'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },

  // 2034
  {
    id: 'buddhist-vesak-2034',
    date: new Date('2034-06-03'),
    title: 'Vesak (Buddha Purnima)',
    summary: 'Commemorates the birth, enlightenment (nirvāṇa), and death (parinirvāṇa) of Gautama Buddha. It is the most important festival for Buddhists worldwide.',
    tags: ['Buddhism', 'Celebration', 'Gautama Buddha'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vesak',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lotus flower',
  },
  {
    id: 'buddhist-magha-puja-2034',
    date: new Date('2034-03-05'),
    title: 'Magha Puja (Fourfold Assembly Day)',
    summary: 'Marks the occasion when 1,250 enlightened disciples of the Buddha gathered to hear his teachings without being summoned.',
    tags: ['Buddhism', 'Sangha', 'Dhamma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Māgha_Pūjā',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'monks meditating',
  },
  {
    id: 'buddhist-asalha-puja-2034',
    date: new Date('2034-07-01'),
    title: 'Asalha Puja (Dharma Day)',
    summary: 'Celebrates the Buddha\'s first sermon, known as the "Dhammacakkappavattana Sutta," where he set the Wheel of Dharma in motion.',
    tags: ['Buddhism', 'Sermon', 'Dharma'],
    tradition: 'Universal',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Asalha_Puja',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'dharma wheel',
  },
  {
    id: 'buddhist-vassa-start-2034',
    date: new Date('2034-07-02'),
    title: 'Vassa (Rains Retreat) Begins',
    summary: 'The start of the three-month annual retreat observed by Theravada practitioners during the wet season, where monks remain in one place.',
    tags: ['Buddhism', 'Theravada', 'Retreat', 'Monasticism'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Vassa',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'rainy season temple',
  },
  {
    id: 'buddhist-kathina-2034',
    date: new Date('2034-10-28'),
    title: 'Kathina Ceremony',
    summary: 'A festival where lay Buddhists offer cloth and other necessities to monks. It takes place in the month following the end of Vassa.',
    tags: ['Buddhism', 'Theravada', 'Offering', 'Community'],
    tradition: 'Theravada',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Kathina',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'saffron robes offering',
  },
  {
    id: 'buddhist-bodhi-day-2034',
    date: new Date('2034-12-08'),
    title: 'Bodhi Day',
    summary: 'Commemorates the day that Gautama Buddha attained enlightenment under the Bodhi tree.',
    tags: ['Buddhism', 'Mahayana', 'Enlightenment', 'Meditation'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Bodhi_Day',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'bodhi tree meditation',
  },
  {
    id: 'buddhist-ullambana-2034',
    date: new Date('2034-08-28'),
    title: 'Ullambana (Ghost Festival)',
    summary: 'A Mahayana festival where offerings are made to ancestors and the spirits of the deceased to relieve their suffering.',
    tags: ['Buddhism', 'Mahayana', 'Ancestors', 'Offering'],
    tradition: 'Mahayana',
    readMoreUrl: 'https://en.wikipedia.org/wiki/Ghost_Festival',
    imageUrl: 'https://placehold.co/600x400.png',
    imageAiHint: 'lanterns festival',
  },
];
